import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarSection from "@/components/Navbar";
import FooterSection from "@/components/FooterSection";
// import { Toast } from "@heroui/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <NavbarSection></NavbarSection>
        <main>

            {children}

        </main>
        <FooterSection></FooterSection>


        {/* <Toast.Provider>
          <Toast>
            <Toast.Indicator />
            <Toast.Content>
              <Toast.Title />
              <Toast.Description />
            </Toast.Content>
            <Toast.ActionButton />
            <Toast.CloseButton />
          </Toast>
        </Toast.Provider> */}

      </body>
        
    </html>
  );
}
